# Generated by Django 5.0.1 on 2024-02-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tech_project_tech_used'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tech',
            new_name='Technology',
        ),
    ]
