# Generated by Django 5.0.1 on 2024-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_title_image_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_desc',
            field=models.CharField(default='Placeholder', max_length=200),
        ),
    ]
