# Generated by Django 5.0.1 on 2024-02-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default='https://github.com/Semaforje/PLACEHOLDER', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='https://PLACEHOLDER.com', max_length=200),
        ),
    ]
