# Generated by Django 5.0.1 on 2024-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_github_link_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=200),
        ),
    ]
