# Generated by Django 5.0.1 on 2024-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_project_github_link_alter_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_details_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images/'),
        ),
    ]
