# Generated by Django 5.0.1 on 2024-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_project_project_details_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_details_check_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_details_github_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images/'),
        ),
    ]
